### ISSUE TITLE
kramdown security alert

### ISSUE THREAD

**Issue by bccufba** [bcc-ufba/bcc-ufba.github.io#6]
@rodrigorgs Sabe como resolver esse alerta?

**Comment by rodrigorgs** [comment]
@christinaflach Qual o contexto? Onde essa mensagem está aparecendo? Deve ser só questão de atualizar a versão de alguma dependência.

**Comment by christinaflach** [comment]
Certo. Ela parou de aparecer, por enquanto. Vou fechar ;-)
